---
- name: create a user and if the user is newly created, update his password
  hosts: all
  become: true
  tasks:
    - name: create a user
      user:
        name: kumar
      register: userdata
    - name: print the logs
      debug:
        var: userdata
    - name: update the password of the user
      user: 
        name: kumar
        password: 12345
      when: 
        userdata.changed==true
