---
- name: uninstall tree git maven java tomcat apache2
  hosts: all
  become: true
  tasks:
    - name: uninstall tree, git, maven, java , tomcat apache2
      apt:
        name: "{{item}}"
        state: absent
      with_items:
        - git
        - maven
        - default-jdk
        - tomcat9
        - apache2
        - tree
