---
- name: quick example on ansible error handling
  hosts: all
  become: true
  tasks:
    - block:
        - name: install tomcat8
          apt: 
           name: tomcat8
           state: present
          notify: restart tomcat8
      rescue:
        - name: install tomcat7
          apt: 
            name: tomcat7
            state: present
          notify: restart tomcat9
      always:
       - name: check url resp
         uri:
           url: http://52.91.156.180:8080
           status_code: 200
  handlers:
    - name: restart tomcat9
      service:
        name: tomcat9
        state: restarted
    - name: restart tomcat8
      service:
        name: tomcat8
        state: restarted
